# Generated by Django 2.1.7 on 2019-03-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190308_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='baths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='address',
            field=models.CharField(default='No Address Found', max_length=100),
        ),
    ]
