# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190319_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='area',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
