# Generated by Django 2.1.7 on 2019-03-20 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_post_available'),
        ('polls', '0011_profile_bio'),
    ]

    operations = [
    ]
