# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_profile_bio'),
        ('polls', '0007_post_available'),
    ]

    operations = [
    ]
