# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_merge_20190321_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='cake', max_length=1000),
        ),
    ]
