# Generated by Django 2.1.7 on 2019-03-22 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20190321_1707'),
        ('polls', '0012_merge_20190319_2236'),
    ]

    operations = [
    ]
