# Generated by Django 2.1.7 on 2019-03-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
