# Generated by Django 2.1.7 on 2019-03-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_remove_review_user'),
        ('polls', '0015_auto_20190322_2050'),
    ]

    operations = [
    ]
