# Generated by Django 2.0.13 on 2019-04-01 20:22

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_remove_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='google_address',
            field=django_google_maps.fields.AddressField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='', max_length=100),
        ),
    ]
