# Generated by Django 2.0.13 on 2019-04-03 19:20

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20190401_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(default='1207 Wertland Street', max_length=100),
        ),
    ]
