# Generated by Django 2.0.13 on 2019-04-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/'),
        ),
    ]
