# Generated by Django 2.0.13 on 2019-04-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20190403_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='post',
            name='google_address',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
