# Generated by Django 2.0.13 on 2019-04-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_review_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
    ]
