# Generated by Django 2.0.13 on 2019-04-07 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_post_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-rating']},
        ),
    ]
