# Generated by Django 2.0.13 on 2019-04-08 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20190407_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['name']},
        ),
    ]
