# Generated by Django 2.0.13 on 2019-04-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_auto_20190414_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='need_roommate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Graduate Student')], default='1', max_length=1),
        ),
    ]
