# Generated by Django 2.0.13 on 2019-04-24 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_postimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='Image',
        ),
    ]
