# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_auto_20190423_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.Post'),
        ),
    ]
