# Generated by Django 2.0.13 on 2019-04-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_auto_20190426_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
