# Generated by Django 2.0.13 on 2019-04-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_auto_20190426_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('u', 'Unspecified'), ('w', 'Woman'), ('m', 'Man'), ('gnc', 'Gender Non-Conforming'), ('t', 'Transgender'), ('pnts', 'Prefer Not To Say')], default='u', max_length=4),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('u', 'Unspecified'), ('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Graduate Student')], default='u', max_length=1),
        ),
    ]
